# Auto-generated by BaseTools/BuildEnv
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/Users/vihaannathan/Desktop/efiloader
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/Users/vihaannathan/Desktop/efiloader/BaseTools
fi
if [ -e /Users/vihaannathan/Desktop/efiloader/BaseTools/Bin/Darwin-arm64 ]
then
  FOUND_TOOLS_PATH_BIN=0
  for DIR in $(echo $PATH | tr ':' ' '); do
    if [ "$DIR" = "/Users/vihaannathan/Desktop/efiloader/BaseTools/Bin/Darwin-arm64" ]; then
      FOUND_TOOLS_PATH_BIN=1
    fi
  done
  if [ $FOUND_TOOLS_PATH_BIN = 0 ]
  then
    export PATH=/Users/vihaannathan/Desktop/efiloader/BaseTools/Bin/Darwin-arm64:$PATH
  fi
fi
